version: '3.8'

services:
  db:
    image: postgres:11.0-alpine
    container_name: database
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql

  bot:
#    image: krivse/fartpark_txya:v1.0
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: bash -c "alembic revision --autogenerate -m 'create table' && alembic upgrade head && python3 -m bot"
    restart: always
    env_file:
      - .env
    networks:
      - tg_bot
    depends_on:
      - db

networks:
  tg_bot:
    driver: bridge
