"""empty message

Revision ID: 1623c6d7c5b7
Revises: 92a21df6df43
Create Date: 2023-03-28 20:30:02.566653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1623c6d7c5b7'
down_revision = '92a21df6df43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
