"""initial migration

Revision ID: 280d33c711e0
Revises: f1f98e86dd6e
Create Date: 2023-03-18 21:15:41.368144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280d33c711e0'
down_revision = 'f1f98e86dd6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('taxi_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'taxi_id')
    # ### end Alembic commands ###
