"""empty message

Revision ID: 35ee91adc067
Revises: 6ee02ae4e9ac
Create Date: 2023-03-28 20:20:46.184956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee91adc067'
down_revision = '6ee02ae4e9ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
