"""empty message

Revision ID: 92a21df6df43
Revises: 35ee91adc067
Create Date: 2023-03-28 20:29:09.557223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a21df6df43'
down_revision = '35ee91adc067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
